name: 部署Blazor应用到GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# 设置权限
permissions:
  contents: read
  pages: write
  id-token: write

# 允许一个并发部署
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # 构建任务
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: 设置 .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
      
      - name: 构建应用
        run: dotnet publish iBlazorWebAssembly/iBlazorWebAssembly.csproj -c Release -o release --nologo
      
      # 修改 base href 和添加 .nojekyll 文件
      - name: 更改 base 标记并创建 .nojekyll
        run: |
          sed -i 's/<base href="\/" \/>/<base href="\.\/" \/>/g' release/wwwroot/index.html
          touch release/wwwroot/.nojekyll
      
      # 配置 GitHub Pages
      - name: 设置 Pages
        uses: actions/configure-pages@v4
        with:
          enablement: true  # 启用 GitHub Pages
      
      # 上传构建物
      - name: 上传构建物
        run: |
          cd release/wwwroot
          zip -r ../../site.zip .
      
      - name: 上传 Pages 构建物
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: site.zip
          retention-days: 1
      
      # 部署到 GitHub Pages
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4