name: 部署 Blazor WebAssembly 到 GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# 设置权限
permissions:
  contents: write
  pages: write
  id-token: write

# 允许一个并发部署
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # 构建任务
  build:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - name: 检出代码
        uses: actions/checkout@v4

      # 设置 .NET SDK
      - name: 设置 .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      # 发布应用
      - name: 构建和发布 Blazor WebAssembly 应用
        run: |
          dotnet restore
          dotnet publish iBlazorWebAssembly/iBlazorWebAssembly.csproj -c Release -o release --nologo

      # 配置 base 标签和特殊文件
      - name: 配置 GitHub Pages 特殊文件
        run: |
          # 确保 base 标签为相对路径
          sed -i 's|<base href="/" />|<base href="./" />|g' release/wwwroot/index.html
          # 添加 .nojekyll 文件禁用 Jekyll 处理
          touch release/wwwroot/.nojekyll
          # 添加 404.html 用于客户端路由
          cp release/wwwroot/index.html release/wwwroot/404.html
          # 添加重定向规则
          echo '/* /index.html 200' > release/wwwroot/_redirects

      # 直接部署到 GitHub Pages 分支
      - name: 部署到 GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: release/wwwroot
          branch: gh-pages
          clean: true