name: 部署到GitHub Pages

on:
  push:
    branches: [ "main" ]  # 当推送到main分支时触发
  workflow_dispatch:      # 允许从GitHub UI手动触发

# 设置GITHUB_TOKEN的权限
permissions:
  contents: read
  pages: write
  id-token: write

# 允许一个并发部署
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # 构建作业
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
          
      - name: 恢复依赖项
        run: dotnet restore
        
      - name: 构建应用
        run: dotnet build iBlazorWebAssembly/iBlazorWebAssembly.csproj -c Release --no-restore
        
      - name: 发布应用
        run: dotnet publish iBlazorWebAssembly/iBlazorWebAssembly.csproj -c Release -o publish
        
      - name: 修改发布的 index.html
        run: |
          sed -i 's|<base href="/" />|<base href="./" />|g' publish/wwwroot/index.html
          
      - name: 添加 .nojekyll 文件
        run: touch publish/wwwroot/.nojekyll
        
      - name: 设置GitHub Pages
        uses: actions/configure-pages@v3
        
      # 添加明确版本的upload-artifact动作，作为依赖项
      - name: 上传构建产物备份
        uses: actions/upload-artifact@v3
        with:
          name: webapp-build
          path: publish/wwwroot
        
      - name: 上传构建产物到Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: publish/wwwroot

  # 部署作业
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 部署到GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2